ERROR_CODES = {
    "AUTH_REQUIRED": "AUTH_REQUIRED",
    "RBAC_DENIED": "RBAC_DENIED",
    "VALIDATION_FAILED": "VALIDATION_FAILED",
    "HAZARD_TICKET_NOT_FOUND": "HAZARD_TICKET_NOT_FOUND",
    "RECHECK_PAYLOAD_INVALID": "RECHECK_PAYLOAD_INVALID",
    "RECTIFY_PAYLOAD_INVALID": "RECTIFY_PAYLOAD_INVALID"
}
